check50: 
  files: &check50_files
    - !exclude "*"
    - !require "beach.bmp"
    - !require "black.bmp"
    - !require "blue.bmp"
    - !require "brightness.c"
    - !require "dart.bmp"
    - !require "night.bmp"
    - !require "white.bmp"

submit50:
  files: *check50_files
